### ISSUE TITLE
Pass wrong param in RepositoryEntityDeleting event in deleteWhere function

### ISSUE THREAD

**Issue by vuletuan** [andersao/l5-repository#710] opened 2020-05-15 02:02 UTC
Version : 2.6.43
Error: Argument 2 passed to Prettus\Repository\Events\RepositoryEventBase::__construct() must be an instance of Illuminate\Database\Eloquent\Model or null, instance of Illuminate\Database\Eloquent\Builder given

```php
    public function deleteWhere(array $where)
    {
        $this->applyScope();

        $temporarySkipPresenter = $this->skipPresenter;
        $this->skipPresenter(true);

        $this->applyConditions($where);

        event(new RepositoryEntityDeleting($this, $this->model)); # it should $this->model->getModel()

        $deleted = $this->model->delete();

        event(new RepositoryEntityDeleted($this, $this->model->getModel()));

        $this->skipPresenter($temporarySkipPresenter);
        $this->resetModel();

        return $deleted;
    }
```

**Comment by bosix** [comment] 2020-05-15 08:18
I can confirm the error. It should be fixed fast since a patch-release introduced this error.

Working: v2.6.42
Not working: v2.6.43

**Comment by bsormagec** [comment] 2020-05-15 08:23
is this good ?

https://github.com/andersao/l5-repository/blob/8c8db9895745dc35eb471a8f048ff9c000a3ccdd/src/Prettus/Repository/Eloquent/BaseRepository.php#L772

**Comment by vuletuan** [comment] 2020-05-15 08:25
> is this good ?
> 
> https://github.com/andersao/l5-repository/blob/8c8db9895745dc35eb471a8f048ff9c000a3ccdd/src/Prettus/Repository/Eloquent/BaseRepository.php#L772

Yes, it is. I think it works

**Comment by bsormagec** [comment] 2020-05-15 08:38
ok releaseing i am remote from computer working on mobile now, please check after i release

**Comment by bsormagec** [comment] 2020-05-15 08:44
released check and give me information.

**Comment by vuletuan** [comment] 2020-05-15 08:52
> released check and give me information.

Thank for your support. It worked.

**Comment by bsormagec** [comment] 2020-05-15 08:55
🆗  thanks for your feedback

**Closed** 2020-05-15 08:55 UTC
