### ISSUE TITLE
make:entity not creating controller in Laravel 5.5

### ISSUE THREAD

**Issue by berzley** [andersao/l5-repository#435] opened 2017-09-08 14:22 UTC
Hello,

I'm using Laravel 5.5.3 with l5-repository v 2.6.22 - fresh install of both.

My issue is that the `make:entity` command is not producing a Controller. All other files are created as expected and the path for controllers is set appropriately.

**Comment by mouggey** [comment] 2017-09-09 12:03
Same case here. The `make:entity` command is not producing a Controller.

**Comment by jdcargile** [comment] 2017-09-11 04:29
+1

**Comment by higormeloap89** [comment] 2017-09-11 16:38
Same case here. The make:entity command is not producing a Controller.

**Comment by SergeiSporyshev** [comment] 2017-09-12 13:34
Guys?

**Comment by cballou** [comment] 2017-09-15 13:12
OP is bad at managing issues and pull requests, but it looks like he may have fixed the issue.

https://github.com/andersao/l5-repository/commit/c28699dbe0823bb7e5f93c4f292018dcc163d5bc

**Comment by dinho-afsn** [comment] 2017-09-22 16:29
Same problem 
[Symfony\Component\Console\Exception\InvalidOptionException]  
  The "--force" option does not exist. 


Can someone solve it?
I'm using the latest version and it does not work with laravel 5.5

**Comment by SergeiSporyshev** [comment] 2017-09-23 05:53
Yeah!
The problem is Laravel 5.5 has own command with signature "make:resource".
I've solved it by change l5-repository command's signature to "make:rest-resource"

**Comment by dinho-afsn** [comment] 2017-09-23 11:56
Thank you for replying, my friend.
But unfortunately it does not work. see the error I get
![captura de tela 2017-09-23 as 08 54 41](https://user-images.githubusercontent.com/5239515/30772951-048c8ffa-a03d-11e7-951a-4630b3da8d9e.png)
![captura de tela 2017-09-23 as 08 54 51](https://user-images.githubusercontent.com/5239515/30772952-088d74ac-a03d-11e7-9ebb-f578b215382e.png)

there is no make: rest-resource

**Comment by SergeiSporyshev** [comment] 2017-09-24 06:38
In vendor/prettus/l5-repository/src/Prettus/Repository/Generators/Commands/ControllerCommand.php
you should replace
    protected $name = 'make:resource';
to
    protected $name = 'make:rest-resource';

**Comment by avatarGit** [comment] 2017-09-25 05:57
same case here..

**Comment by dinho-afsn** [comment] 2017-09-25 15:48
Thank you my friend SergeiSporyshev. Now it worked perfectly!!!

**Comment by eullercdr** [comment] 2017-10-27 13:48
@Maras0830 Can you send-me a new PR for this problem please. I had a problem, and i losed your commit.

**Comment by Maras0830** [comment] 2017-10-28 17:17
@eullercdr https://github.com/andersao/l5-repository/pull/466

**Comment by eullercdr** [comment] 2017-10-28 20:27
Thanks @Maras0830 , merged. You are the guy!

**Closed** 2017-10-28 20:28 UTC

**Comment by qiutuleng** [comment] 2017-10-31 01:48
@eullercdr The latest version still has this problem

**Comment by Maras0830** [comment] 2017-10-31 13:29
@qiutuleng  sorry I submit wrong branch in pr, i resent the new.

@eullercdr https://github.com/andersao/l5-repository/pull/470
